services:

  mongo:
    image: mongo:7.0.14-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: users
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongodb/data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  postgres:
    container_name: postgres_container
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_DB=: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_password}
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped
